remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Lucas Hardy's Game Portfolio
description: A page to host all of my projects, code and more!
Header: 2025 Terrorbyte Game Jam
description: I recently competed in the 2025 Terrorbyte Game Jam and brough home 2nd place with my team.
